"""Hugging Face dataset publishing and dataset card generation (FR-13–FR-15, AD-5, AD-9).

Generic over the Scenario schema — no concrete Market Model is imported.
"""
from __future__ import annotations

import dataclasses
import json
from typing import Sequence

import numpy as np

from ..interface import Scenario

# Fixed column schema from Story 3.1 (export_parquet).  Listed here so the
# dataset card and schema-conformance checks always reference the same source
# of truth without importing from a sibling story's module.
PARQUET_COLUMNS = (
    "observation",
    "latent_state",
    "seed",
    "prng_key_info",
    "model_name",
    "model_version",
    "parameters",
    "time_grid",
    "n_paths",
    "library_version",
    "dataset_version",
    "generated_at",
)

_COLUMN_DESCRIPTIONS = {
    "observation":     ("list<float64>", "Simulated asset-price path; one row per path"),
    "latent_state":    ("list<float64>", "Latent-state path (e.g. variance); empty list for models with no latent process"),
    "seed":            ("int64",         "Integer PRNG seed used to reproduce this batch"),
    "prng_key_info":   ("string",        "Description of JAX PRNGKey derivation from seed"),
    "model_name":      ("string",        "Market Model class name (e.g. BlackScholes, Heston, RoughBergomi)"),
    "model_version":   ("string",        "Version of the Market Model specification"),
    "parameters":      ("string",        "JSON-encoded Market Model scalar parameters"),
    "time_grid":       ("string",        "JSON-encoded array of simulation time points"),
    "n_paths":         ("int64",         "Number of independent simulation paths in this batch"),
    "library_version": ("string",        "quantscenariobench library version that generated this batch"),
    "dataset_version": ("string",        "Dataset version identifier — independent of library_version (FR-14, AD-11)"),
    "generated_at":    ("string",        "UTC ISO-8601 timestamp of dataset generation"),
}

_CARD_TEMPLATE = """\
---
license: mit
tags:
  - finance
  - simulation
  - market-scenarios
  - quantitative-finance
  - quantscenariobench
dataset_info:
  version: {dataset_version}
---

# {model_name} Benchmark Dataset

Generated by [QuantScenarioBench](https://github.com/tim-nish/QuantScenarioBench)
v{library_version} — library version **{library_version}**, dataset version **{dataset_version}**.

> **Versioning note (FR-14, AD-11):** `dataset_version` and `library_version` are
> independent identifiers. Regenerating a dataset with different parameters or a new
> seed increments only `dataset_version`; a library release that adds a new Market
> Model does not force a dataset re-generation.

---

## Column Schema

All QuantScenarioBench v1 Benchmark Datasets share the same top-level column schema
regardless of which Market Model produced them (FR-13):

| Column | Type | Description |
|--------|------|-------------|
{schema_table_rows}

---

## Market Model

**Model:** `{model_name}`

**Parameters (used to generate this dataset):**

```json
{parameters_json}
```

---

## Simulation Configuration

| Field | Value |
|-------|-------|
| Time Grid steps | {n_steps} |
| t₀ | {t0} |
| t₁ | {t1} |
| Number of paths | {n_paths} |

---

## Versioning

| Field | Value |
|-------|-------|
| Library version | `{library_version}` |
| Dataset version | `{dataset_version}` |

---

## Reproducibility Caveat

Simulation paths are **bit-identical across runs on the same computational backend**
(CPU / GPU / TPU) when using the same `seed`, `library_version`, and model parameters.

**Cross-backend bit-identity is not guaranteed.** JAX floating-point operations may
produce different bit patterns across hardware backends (e.g. CPU vs. GPU) even with
identical inputs, seeds, and library versions. The `seed`, `prng_key_info`, and
`library_version` columns document the full provenance of every batch so that
differences can be traced to backend changes rather than parameter or code drift.
"""


def generate_dataset_card(scenario: Scenario) -> str:
    """Generate a Hugging Face dataset card (README.md) for a published Scenario batch.

    The card contains all six required fields (FR-15):
    1. Column schema
    2. Market Model name and parameter values
    3. TimeGrid and n_paths
    4. Library version
    5. Dataset version identifier
    6. Backend-scoped reproducibility caveat

    Parameters
    ----------
    scenario:
        A :class:`~quantscenariobench.interface.Scenario` whose metadata
        provides all card content. Any Scenario from ``simulate()`` is valid.

    Returns
    -------
    str
        Markdown-formatted dataset card text suitable for upload as README.md.
    """
    meta = scenario.metadata

    # --- parameters JSON ---
    params = meta.parameters
    try:
        field_dict = {f.name: getattr(params, f.name) for f in dataclasses.fields(params)}  # type: ignore
    except TypeError:
        field_dict = vars(params)
    serializable: dict = {}
    for k, v in field_dict.items():
        if hasattr(v, "item"):
            serializable[k] = v.item()
        elif hasattr(v, "tolist"):
            serializable[k] = v.tolist()
        else:
            serializable[k] = v
    params_json = json.dumps(serializable, indent=2)

    # --- time grid ---
    tg = meta.time_grid
    ts = np.array(tg.t)
    t0, t1, n_steps = float(ts[0]), float(ts[-1]), int(ts.shape[0])

    # --- schema table rows ---
    rows = "\n".join(
        f"| `{col}` | `{_COLUMN_DESCRIPTIONS[col][0]}` | {_COLUMN_DESCRIPTIONS[col][1]} |"
        for col in PARQUET_COLUMNS
    )

    return _CARD_TEMPLATE.format(
        model_name=meta.model_name,
        library_version=meta.library_version,
        dataset_version=meta.dataset_version,
        schema_table_rows=rows,
        parameters_json=params_json,
        n_steps=n_steps,
        t0=t0,
        t1=t1,
        n_paths=meta.n_paths,
    )


def publish_to_hub(
    scenarios: Sequence[Scenario],
    repo_id: str,
    *,
    token: str | None = None,
    commit_message: str = "Upload QuantScenarioBench benchmark dataset",
    basket_metadata=None,
) -> str:
    """Publish a batch of Scenarios to the Hugging Face Hub as a dataset.

    Writes a Parquet file and dataset card, then uploads both to the Hub.
    The export pipeline is generic — no concrete Market Model is imported here
    (AD-5, FR-10).

    Parameters
    ----------
    scenarios:
        One or more :class:`~quantscenariobench.interface.Scenario` objects
        from :func:`~quantscenariobench.api.simulate`.
    repo_id:
        Hugging Face Hub repository ID, e.g. ``"my-org/black-scholes-benchmark"``.
    token:
        HF Hub API token. Falls back to ``HF_TOKEN`` environment variable or
        a prior ``huggingface-cli login`` session if ``None``.
    commit_message:
        Commit message recorded in the Hub repository.
    basket_metadata:
        Optional :class:`~quantscenariobench.interface.BasketMetadata` from
        :func:`~quantscenariobench.api.simulate_correlated_basket` (FR-47,
        AD-36) — forwarded additively to :func:`export_parquet` so it
        survives Hub publish/reload unchanged. None (the default) leaves
        the uploaded Parquet schema exactly as before this parameter
        existed.

    Returns
    -------
    str
        URL of the published dataset on the Hugging Face Hub.

    Raises
    ------
    ImportError
        If ``huggingface_hub`` is not installed.
    """
    try:
        import huggingface_hub as hf
    except ImportError as exc:
        raise ImportError(
            "publish_to_hub requires huggingface_hub. "
            "Install it with: pip install huggingface_hub"
        ) from exc

    from ._parquet import export_parquet  # intra-package; not a cross-subpackage import
    import tempfile
    from pathlib import Path

    card_text = generate_dataset_card(scenarios[0]) if scenarios else ""

    api = hf.HfApi(token=token)
    api.create_repo(repo_id=repo_id, repo_type="dataset", exist_ok=True, token=token)

    with tempfile.TemporaryDirectory() as tmpdir:
        parquet_path = Path(tmpdir) / "train.parquet"
        export_parquet(scenarios, parquet_path, basket_metadata=basket_metadata)

        api.upload_file(
            path_or_fileobj=str(parquet_path),
            path_in_repo="data/train.parquet",
            repo_id=repo_id,
            repo_type="dataset",
            commit_message=commit_message,
            token=token,
        )
        api.upload_file(
            path_or_fileobj=card_text.encode(),
            path_in_repo="README.md",
            repo_id=repo_id,
            repo_type="dataset",
            commit_message=commit_message,
            token=token,
        )

    return f"https://huggingface.co/datasets/{repo_id}"
